package id.biojelan.app.ui.strings

/**
 * Implementasi BioStrings dalam Bahasa Indonesia.
 * Isi string persis sama dengan yang sekarang hardcoded di UI.
 */
object IdStrings : BioStrings {

    // ============================================================ Common
    override val appName = "BioJelan"
    override val reload = "Muat ulang"
    override val back = "Kembali"
    override val save = "Simpan"
    override val cancel = "Batalkan"
    override val reject = "Tolak"
    override val accept = "Terima"
    override val close = "Tutup"
    override val or = "atau"

    // ============================================================ Auth
    override val welcomeTitle = "Selamat datang di BioJelan"
    override val welcomeSubtitle = "Tampilan akan menyesuaikan peran Anda"
    override val createAccountTitle = "Buat akun BioJelan"
    override val createAccountSubtitle = "Akun Anda terdaftar sebagai Klien. Untuk menjadi Agen, hubungi tim Kilang"
    override val signIn = "Masuk"
    override val signUp = "Daftar"
    override val forgotPasswordLink = "Lupa kata sandi?"
    override val forgotPasswordTitle = "Lupa kata sandi"
    override val forgotPasswordHeadline = "Kami kirim tautan reset ke email Anda"
    override val forgotPasswordBody = "Masukkan email yang terdaftar. Tautan untuk membuat kata sandi baru akan dikirim ke sana."
    override val sendResetLink = "Kirim tautan reset"
    override val resetSentNote = "Jika email terdaftar, tautan reset sudah dikirim. Cek kotak masuk (dan folder spam)."
    override val guestEntry = "Masuk sebagai tamu"
    override val retryButton = "Coba lagi"

    override val fieldFullName = "Nama lengkap"
    override val fieldEmail = "Email"
    override val fieldPassword = "Kata sandi"
    override val fieldRepeatPassword = "Ulangi kata sandi"
    override val placeholderName = "Nama Anda"
    override val placeholderEmail = "nama@email.com"
    override val placeholderPasswordMin = "Minimal 8 karakter"
    override val placeholderPasswordYours = "Kata sandi Anda"
    override val placeholderRepeatPassword = "Ketik ulang kata sandi"

    // ============================================================ Navigation tabs
    override val tabHome = "Beranda"
    override val tabFindAgent = "Cari Agen"
    override val tabTransactions = "Transaksi"
    override val tabStock = "Stok"
    override val tabPickup = "Pickup"
    override val tabHistory = "Riwayat"
    override val tabProfile = "Profil"

    // ============================================================ Klien Home
    override val priceCaption = "Harga acuan Kilang · berlaku untuk semua Agen"
    override val quickActionFindAgent = "Cari Agen"
    override val quickActionHistory = "Riwayat"
    override val quickActionMyId = "ID Saya"
    override val sectionAgenBioJelan = "Agen BioJelan"
    override val viewAll = "Lihat semua"
    override val noAgentsRegistered = "Belum ada Agen terdaftar."
    override val klienInfoNote = "Jual minyak jelantah Anda ke Agen. Agen mencatat transaksi, lalu Anda konfirmasi di sini — pembayaran diselesaikan langsung dengan Agen."
    override val confirmTransaction = "Konfirmasi transaksi"
    override val open = "Buka"
    override val closed = "Tutup"
    override fun pendingTxBody(agenName: String, volume: String) =
        "$agenName mencatat penjualan $volume minyak jelantah atas nama Anda."
    override val cancelRequestTitle = "Permintaan pembatalan"
    override fun cancelRequestedTxBody(agenName: String, volume: String) =
        "$agenName mengajukan pembatalan transaksi $volume minyak jelantah ini."
    override val approveCancelLabel = "Setuju Dibatalkan"
    override val keepTransactionLabel = "Pertahankan"

    // ============================================================ Agen Home
    override val priceCaptionAgen = "Harga acuan Kilang · dipakai saat mencatat transaksi"
    override val todayTransactions = "Transaksi hari ini"
    override val collectedToday = "Terkumpul hari ini"
    override val valueToday = "Nilai hari ini"
    override val currentStockLabel = "STOK SAAT INI"
    override val readyForPickup = "Siap dijemput Kilang"
    override fun remainingToThreshold(remaining: String) = "$remaining lagi menuju ambang"
    override val newTransaction = "Input Transaksi Baru"
    override val recentActivity = "Aktivitas terakhir"
    override val seeAll = "Semua"
    override val noTransactionsYet = "Belum ada transaksi."
    override val noTransactionsAgenHint = "Belum ada transaksi. Catat penjualan pertama dari Klien lewat tombol di atas."

    // ============================================================ Agen Stock
    override val stockTitle = "Stok Minyak"
    override fun thresholdCaption(threshold: String) = "dari ambang batas $threshold"
    override val aboveThresholdNote = "Sudah lewati ambang — menunggu jadwal Kilang"
    override val stockThresholdInfo = "Setelah stok melewati ambang, Kilang akan menjadwalkan penjemputan. Ambang batas ditentukan oleh Kilang."
    override val stockMovement = "Riwayat pergerakan stok"
    override val noStockMovement = "Belum ada pergerakan. Stok bertambah saat Klien menerima transaksi."
    override val stockCorrectionLink = "Ada selisih catatan stok? Laporkan di sini"
    override val stockCorrectionToast = "Fitur koreksi stok belum tersedia — hubungi Kilang untuk perbaikan catatan."
    override val stockHistoryToast = "Riwayat lengkap pergerakan stok"
    override val stockIncoming = "Masuk"
    override val stockWaiting = "Menunggu"
    override val stockCancelled = "Dibatalkan"
    override fun transactionDash(name: String) = "Transaksi — $name"

    // ============================================================ Agen Pickup
    override val pickupTitle = "Info Pickup"
    override val pickupSectionTitle = "Status penjemputan"
    override val pickupNoneScheduled = "Belum ada penjemputan yang dijadwalkan Kilang."
    override val pickupStatusAssigned = "Driver ditugaskan"
    override val pickupStatusOtw = "Driver dalam perjalanan"
    override val pickupStatusCompleted = "Penjemputan selesai"
    override val pickupStatusCancelled = "Penjemputan dibatalkan"
    override val pickupNoteAssigned = "Kilang sudah menugaskan Driver. Siapkan dirigen Anda."
    override val pickupNoteOtw = "Driver sedang menuju lokasi Anda."
    override val pickupNoteCompleted = "Minyak sudah diambil Driver — stok akan diperbarui Kilang."
    override fun pickupUpdatedAt(time: String) = "Diperbarui $time"
    override val pickupStepAssigned = "Ditugaskan"
    override val pickupStepOtw = "Dalam perjalanan"
    override val pickupStepCompleted = "Selesai"
    override val pickupIdLabel = "ID Pickup"
    override val pickupScheduleLabel = "Jadwal pickup"

    // ============================================================ Agen Transactions
    override val transactionsTitle = "Transaksi"
    override val transactionDetailTitle = "Detail transaksi"
    override val todayLabel = "Hari ini"
    override val volumeToday = "Volume hari ini"
    override val noTransactionsTitle = "Belum ada transaksi"
    override val noTransactionsHint = "Tekan tombol + untuk mencatat penjualan dari Klien."
    override val transactionButton = "Transaksi"
    override val pendingAgenNote = "Menunggu Klien menerima atau menolak di app-nya. Stok Anda bertambah setelah Klien menerima."
    override val rejectedAgenNote = "Klien menolak transaksi ini. Stok Anda tidak berubah."
    override val cancelRequestedAgenNote = "Menunggu Klien menyetujui pengajuan pembatalan Anda."
    override val cancelledAgenNote = "Transaksi ini dibatalkan (disetujui Klien). Stok Anda tidak berubah."
    override val requestCancelTransaction = "Ajukan Pembatalan"

    override val labelTransactionId = "ID Transaksi"
    override val labelDate = "Tanggal"
    override val labelAgent = "Agen"
    override val labelClient = "Klien"
    override val labelVolume = "Volume"
    override val labelPricePerLiter = "Harga / liter"
    override val labelTotal = "Total"
    override val labelStatus = "Status"

    override val newTransactionTitle = "Input Transaksi Baru"
    override val newTransactionNote = "Isi email atau nomor HP Klien. Setelah dikirim, Klien akan diminta menerima atau menolak di app-nya."
    override val fieldClientEmail = "Email Klien"
    override val fieldClientPhone = "No. HP Klien"
    override val fieldVolume = "Volume minyak (liter)"
    override val fieldTransactionNote = "Catatan (opsional)"
    override val placeholderClientEmail = "email@contoh.com"
    override val placeholderClientPhone = "08xxxxxxxxxx"
    override val placeholderVolume = "mis. 12,5"
    override val placeholderTransactionNote = "mis. dirigen kuning, jenjeng II"
    override val checkingClientNote = "Memeriksa data Klien…"
    override fun clientFoundNote(name: String) = "Klien ditemukan: $name"
    override val clientNotFoundNote = "Klien belum terdaftar di BioJelan. Periksa lagi email/No. HP-nya."
    override val priceCalculatedByServerNote = "Harga & total dihitung otomatis oleh sistem berdasarkan harga aktif dari Kilang — akan terlihat setelah transaksi terkirim."
    override val submitToClient = "Kirim ke Klien"

    override val errorClientContactRequired = "Isi email atau No. HP Klien."
    override val errorVolumeRequired = "Masukkan volume lebih dari 0."
    override val errorVolumeTooLarge = "Volume terlalu besar — periksa kembali."

    // ============================================================ Klien History
    override val historyTitle = "Riwayat"
    override val transactionsCount = "Transaksi"
    override val oilSold = "Minyak terjual"
    override val totalReceived = "Total diterima"
    override val noHistoryTitle = "Belum ada transaksi"
    override val noHistoryHint = "Transaksi dengan Agen akan muncul di sini."
    override val pendingKlienNote = "Periksa jumlah dan harga. Terima jika sudah sesuai dengan yang Anda serahkan ke Agen; tolak jika tidak."
    override val rejectNotUndoable = "Penolakan tidak dapat diurungkan."
    override val yesReject = "Ya, tolak"
    override val approveCancelNotUndoable = "Persetujuan pembatalan tidak dapat diurungkan."
    override val yesApproveCancel = "Ya, setujui"

    // ============================================================ Guest
    override val guestBannerTitle = "Lihat sebagai tamu."
    override val guestBannerBody = "Daftar untuk mulai menjual minyak jelantah dan melihat riwayat transaksi Anda. Ketuk untuk mendaftar."
    override val guestPriceCaption = "Harga jelantah hari ini · berlaku untuk semua Agen"
    override val guestUpsellTitle = "Daftar untuk lanjut"
    override val guestUpsellBody = "Sebagai tamu, Anda hanya dapat melihat lokasi Agen di peta dan harga jelantah terkini. Daftar terlebih dahulu untuk mulai menjual minyak jelantah, melihat riwayat transaksi, dan mengatur profil."
    override val registerNow = "Daftar Sekarang"
    override val maybeLater = "Nanti dulu"

    // ============================================================ Profile
    override val profileTitle = "Profil"
    override val roleAgent = "Agen"
    override val roleClient = "Klien"
    override val sectionAccountData = "Data akun"
    override val sectionAgentData = "Data Agen"
    override val sectionSettings = "Pengaturan"
    override val labelPhone = "Telepon"
    override val labelIdAgent = "ID Agen"
    override val labelIdClient = "ID Klien"
    override val labelAddress = "Alamat"
    override val labelOperatingHours = "Jam operasional"
    override val labelBankAccount = "Rekening"
    override val labelStockThreshold = "Ambang stok"
    override val notFilled = "Belum diisi"
    override val setByKilang = "ditentukan Kilang"
    override val editProfile = "Ubah profil"
    override val changePassword = "Ubah kata sandi"
    override val logout = "Keluar"
    override val deleteAccount = "Hapus akun"

    override val editProfileTitle = "Ubah profil"
    override val fieldName = "Nama"
    override val fieldPhone = "Nomor telepon"
    override val fieldAddress = "Alamat"
    override val fieldBankName = "Nama bank"
    override val fieldAccountNumber = "Nomor rekening"
    override val fieldOpenTime = "Buka"
    override val fieldCloseTime = "Tutup"
    override val fieldOpenDays = "Hari buka"
    override val saveChanges = "Simpan perubahan"
    override val errorNameRequired = "Nama wajib diisi."
    override val errorTimeFormat = "Format HH:mm"
    override val placeholderPhone = "08xxxxxxxxxx"
    override val placeholderAddress = "Alamat lengkap"
    override val placeholderBankName = "mis. BCA"
    override val placeholderOpenTime = "08:00"
    override val placeholderCloseTime = "17:00"

    override val changePasswordTitle = "Ubah kata sandi"
    override val fieldCurrentPassword = "Kata sandi saat ini"
    override val fieldNewPassword = "Kata sandi baru"
    override val fieldRepeatNewPassword = "Ulangi kata sandi baru"
    override val hintMinChars = "Minimal 8 karakter"
    override val errorCurrentPasswordRequired = "Kata sandi saat ini wajib diisi."
    override val errorMinChars = "Minimal 8 karakter."
    override val errorConfirmMismatch = "Konfirmasi tidak cocok."
    override val savePassword = "Simpan kata sandi"

    override val deleteAccountTitle = "Hapus akun"
    override val deleteAccountWarning = "Akun beserta datanya akan dihapus permanen dan tidak bisa dipulihkan."
    override val deleteAccountConfirmLabel = "Ketik HAPUS untuk melanjutkan"
    override val deleteAccountConfirmWord = "HAPUS"
    override val deleteMyAccount = "Hapus akun saya"

    // ============================================================ Transaction status labels
    override fun txStatusLabel(status: String, isKlien: Boolean): String = when (status.trim().lowercase()) {
        "pending" -> if (isKlien) "Menunggu Anda" else "Menunggu Klien"
        "accepted" -> if (isKlien) "Selesai" else "Diterima"
        "cancelled", "canceled" -> "Dibatalkan"
        else -> "—"
    }
    override val statusCancelled = "Dibatalkan"

    // ============================================================ Greeting
    override fun greeting(hour: Int): String = when {
        hour < 11 -> "Selamat pagi"
        hour < 15 -> "Selamat siang"
        hour < 18 -> "Selamat sore"
        else -> "Selamat malam"
    }

    // ============================================================ Date/Time
    override fun relativeToday(time: String) = "Hari ini, $time"
    override fun relativeYesterday(time: String) = "Kemarin, $time"
    override val everyDay = "Setiap hari"
    override val hoursNotSet = "Jam belum diatur"
    override val timezone = "WIB"
    override val monthNames = listOf("Jan", "Feb", "Mar", "Apr", "Mei", "Jun", "Jul", "Agu", "Sep", "Okt", "Nov", "Des")

    // ============================================================ Errors
    override val networkError = "Tidak dapat terhubung ke server. Periksa koneksi internet Anda."
    override val sessionExpired = "Sesi Anda berakhir. Silakan masuk kembali."
    override fun serverError(code: Int) = "Terjadi kesalahan pada server ($code)."
    override val parseError = "Format data dari server tidak sesuai."

    // ============================================================ ID overlay
    override val myIdTitle = "ID Saya"
    override val defaultNickname = "Sobat BioJelan"
}
